name:  First Github Actions

on:
   push
jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install cowsay 
      uses: sudo apt-get install cowsay -y

    - name: Execute Cowsay CMD 
      uses: cowsay -f dragon "Run for a cover, I am a DRAGON....ROWR" >> dragon.txt

    - name: sleep for 30 seconds
      uses: sleep 30 seconds
  test_jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      run: sleep 10
    - name: test file exists
      run: grep -i "dragon" dragon.txt
  deploy_job:
    runs-on: ubuntu-latest
    steps:
    - name: Read File
      run: cat dragon.txt
      
    - name: Deploy
      run: echo Deploying....  

      
